jobs:
  endpoints-tests:
    if: github.repository == 'aws/aws-sdk-java-v2'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-west-2
        role-duration-seconds: 7200
        role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
    - continue-on-error: true
      name: Run endpoints test
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: aws-sdk-java-v2-endpoints-test
  jdk11-build:
    if: github.repository == 'aws/aws-sdk-java-v2'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-west-2
        role-duration-seconds: 7200
        role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
    - continue-on-error: true
      name: Run JDK11 build
      timeout-minutes: 120
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: aws-sdk-java-v2-JDK11
  jdk17-build:
    if: github.repository == 'aws/aws-sdk-java-v2'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-west-2
        role-duration-seconds: 7200
        role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
    - continue-on-error: true
      name: Run JDK17 build
      timeout-minutes: 120
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: aws-sdk-java-v2-JDK17
  jdk21-build:
    if: github.repository == 'aws/aws-sdk-java-v2'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-west-2
        role-duration-seconds: 7200
        role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
    - continue-on-error: true
      name: Run JDK21 build
      timeout-minutes: 120
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: aws-java-sdk-v2-JDK21
  jdk8-build:
    if: github.repository == 'aws/aws-sdk-java-v2'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-west-2
        role-duration-seconds: 7200
        role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
    - continue-on-error: true
      name: Run JDK8 build
      timeout-minutes: 120
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: aws-sdk-java-v2
  native-image-test:
    if: github.repository == 'aws/aws-sdk-java-v2'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-west-2
        role-duration-seconds: 7200
        role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
    - continue-on-error: true
      name: Run native image test
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: aws-sdk-java-v2-native-image-test
  sonar-cloud-build:
    if: github.repository == 'aws/aws-sdk-java-v2'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-west-2
        role-duration-seconds: 7200
        role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
    - continue-on-error: true
      env:
        BASE: ${{ github.base_ref }}
        BRANCH: ${{ github.head_ref || 'master'}}
        PR: ${{ github.event.number }}
      name: Run sonar-cloud analysis
      timeout-minutes: 120
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        env-vars-for-codebuild: 'PR,

          BRANCH,

          BASE

          '
        project-name: aws-sdk-java-v2-sonar
  windows-jdk8-build:
    if: github.repository == 'aws/aws-sdk-java-v2'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-west-2
        role-duration-seconds: 7200
        role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
    - continue-on-error: true
      name: Run JDK8 windows build
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: aws-sdk-java-v2-JDK8-windows
name: AWS CodeBuild CI
on:
  repository_dispatch:
    types: trigger-ga___codebuild-ci.yml
permissions:
  id-token: write
