jobs:
  handle-stale-discussions:
    if: github.repository == 'aws/aws-sdk-java-v2'
    name: Handle stale discussions
    permissions:
      discussions: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      name: Stale discussions action
      uses: aws-github-ops/handle-stale-discussions@v1
      with:
        close-answered-discussion: false
        close-stale-as-answered: false
name: HandleStaleDiscussions
on:
  repository_dispatch:
    types: trigger-ga___handle-stale-discussions.yml
